"""Tests for the modern email shell.

These exercise ``render_modern_email_html`` and the markdown→HTML
front-door (``render_html_body``) to confirm the design language —
pansy logo header, hero, color-bar section titles, three-segment
footer — survives the markdown sanitisation pipeline end to end.
"""
from __future__ import annotations


def test_modern_shell_includes_design_chrome() -> None:
    """The shell must include the brand chrome and footer signature."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html(
        "<p>hello</p>",
        model="claude-sonnet-4-5",
        date="2026-04-25",
        weekday="星期五",
        generated_at="07:31",
        language="zh-CN",
    )
    # Page-level chrome — language drives the lang attribute.
    assert html.startswith("<!doctype html>")
    assert 'lang="zh-CN"' in html
    # Header — wordmark + date with weekday suffix
    assert "HyacineAI" in html
    assert "2026-04-25" in html
    assert "星期五" in html
    # Footer signature line and "Generated by ... powered by"
    assert "你的清晨第一封邮件" in html
    assert "Generated by HyacineAI" in html
    assert "claude-sonnet-4-5" in html
    # Privacy line in the footer
    assert "本邮件由你本机自动生成" in html


def test_h2_emoji_prefix_drives_color_bar() -> None:
    """Each LLM section emoji should be stripped and mapped to an accent."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html("<h2>🔴 今日必做</h2><h2>⚪ FYI</h2>")
    # 🔴 → pinkDeep, ⚪ → goldDeep — the bare emoji must be removed from text.
    assert "🔴" not in html
    assert "⚪" not in html
    assert "今日必做" in html
    assert "FYI" in html
    assert "#E88BA8" in html  # pink bar
    assert "#B8893B" in html  # gold bar


def test_unknown_h2_falls_back_to_default_accent() -> None:
    """Headings without a known emoji prefix get the lavender default bar."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html("<h2>Something else</h2>")
    assert "Something else" in html
    assert "#9A7ECC" in html  # default accent (lavender)


def test_render_html_body_passes_markdown_through_shell() -> None:
    """Bold markdown survives the full pipeline into a styled <strong>."""
    from hyacine.graph.send import render_html_body

    html = render_html_body(
        "**bold**",
        model="kimi-k2-0905-preview",
        date="2026-04-25",
        weekday="Friday",
    )
    assert "<strong" in html
    assert "bold" in html
    # Footer chip must reflect the supplied model id.
    assert "kimi-k2-0905-preview" in html
    # Header should include the English weekday.
    assert "Friday" in html


def test_render_html_body_default_footer_when_model_missing() -> None:
    """No model → 'your local LLM' fallback renders without crashing."""
    from hyacine.graph.send import render_html_body

    html = render_html_body("# hi")
    assert "your local LLM" in html


def test_header_and_footer_escape_user_supplied_strings() -> None:
    """Crafted model/date/weekday must not punch through into markup."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html(
        "<p>body</p>",
        model='</span><script>alert(1)</script>',
        date="<bad>",
        weekday="evil&day",
        generated_at='">"',
    )
    # No raw script/markup punched through.
    assert "<script>alert(1)</script>" not in html
    assert "<bad>" not in html
    # Escaped variants present.
    assert "&lt;script&gt;" in html
    assert "&lt;bad&gt;" in html
    assert "evil&amp;day" in html


def test_nested_lists_keep_structure() -> None:
    """Outer <li> styling must not eat the closing tag of an inner <li>."""
    from hyacine.graph.email_render import render_modern_email_html

    nested = "<ul><li>outer<ul><li>inner</li></ul></li></ul>"
    html = render_modern_email_html(nested)
    # Both list items present and the structure is intact.
    assert html.count("<li") == 2
    assert html.count("</li>") == 2
    assert "outer" in html
    assert "inner" in html


def test_link_with_title_attribute_keeps_attrs_and_styles() -> None:
    """Anchor styling must preserve href + title (and any other attrs)."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html(
        '<p>see <a href="https://example.com" title="t">site</a></p>'
    )
    assert 'href="https://example.com"' in html
    assert 'title="t"' in html
    # Style was injected onto the styled anchor.
    assert "border-bottom:1px solid" in html


def test_render_html_fragment_returns_no_doctype() -> None:
    """Fragment renderer must not wrap its body in a full HTML document."""
    from hyacine.graph.send import render_html_fragment

    fragment = render_html_fragment("# embedded")
    assert "<!doctype html>" not in fragment.lower()
    assert "<html" not in fragment.lower()
    assert "<h1" in fragment
    assert "embedded" in fragment


def test_html_lang_reflects_configured_language() -> None:
    """``language`` config must drive ``<html lang>`` (BCP-47 mapping)."""
    from hyacine.graph.send import render_html_body

    html_zh = render_html_body("hi", language="zh-CN")
    assert '<html lang="zh-CN">' in html_zh

    html_en = render_html_body("hi", language="en")
    assert '<html lang="en">' in html_en

    html_ja = render_html_body("hi", language="ja")
    assert '<html lang="ja">' in html_ja

    # Empty / unknown → defaults to ``en``, not the previous hardcoded ``zh-CN``.
    html_default = render_html_body("hi")
    assert '<html lang="en">' in html_default

    # Unrecognised codes (e.g. an unsupported preset like ``fr-FR``)
    # also resolve to ``en`` rather than passing through unchanged.
    html_unknown = render_html_body("hi", language="fr-FR")
    assert '<html lang="en">' in html_unknown
