"""Tests for the modern email shell.

These exercise ``render_modern_email_html`` and the markdown→HTML
front-door (``render_html_body``) to confirm the design language —
pansy logo header, hero, color-bar section titles, three-segment
footer — survives the markdown sanitisation pipeline end to end.
"""
from __future__ import annotations


def test_modern_shell_includes_design_chrome() -> None:
    """The shell must include the brand chrome and footer signature."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html(
        "<p>hello</p>",
        model="claude-sonnet-4-5",
        date="2026-04-25",
        weekday="星期五",
        generated_at="07:31",
    )
    # Page-level chrome
    assert html.startswith("<!doctype html>")
    assert 'lang="zh-CN"' in html
    # Header — wordmark + date with weekday suffix
    assert "HyacineAI" in html
    assert "2026-04-25" in html
    assert "星期五" in html
    # Footer signature line and "Generated by ... powered by"
    assert "你的清晨第一封邮件" in html
    assert "Generated by HyacineAI" in html
    assert "claude-sonnet-4-5" in html
    # Privacy line in the footer
    assert "本邮件由你本机自动生成" in html


def test_h2_emoji_prefix_drives_color_bar() -> None:
    """Each LLM section emoji should be stripped and mapped to an accent."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html("<h2>🔴 今日必做</h2><h2>⚪ FYI</h2>")
    # 🔴 → pinkDeep, ⚪ → goldDeep — the bare emoji must be removed from text.
    assert "🔴" not in html
    assert "⚪" not in html
    assert "今日必做" in html
    assert "FYI" in html
    assert "#E88BA8" in html  # pink bar
    assert "#B8893B" in html  # gold bar


def test_unknown_h2_falls_back_to_default_accent() -> None:
    """Headings without a known emoji prefix get the lavender default bar."""
    from hyacine.graph.email_render import render_modern_email_html

    html = render_modern_email_html("<h2>Something else</h2>")
    assert "Something else" in html
    assert "#9A7ECC" in html  # default accent (lavender)


def test_render_html_body_passes_markdown_through_shell() -> None:
    """Bold markdown survives the full pipeline into a styled <strong>."""
    from hyacine.graph.send import render_html_body

    html = render_html_body(
        "**bold**",
        model="kimi-k2-0905-preview",
        date="2026-04-25",
        weekday="Friday",
    )
    assert "<strong" in html
    assert "bold" in html
    # Footer chip must reflect the supplied model id.
    assert "kimi-k2-0905-preview" in html
    # Header should include the English weekday.
    assert "Friday" in html


def test_render_html_body_default_footer_when_model_missing() -> None:
    """No model → 'your local LLM' fallback renders without crashing."""
    from hyacine.graph.send import render_html_body

    html = render_html_body("# hi")
    assert "your local LLM" in html
